name: Python Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]
    
    steps:
      - name: Install builder
        run: |
          set -e
          uname -a
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential python-dev protobuf-compiler libprotobuf-dev libtokyocabinet-dev python-psycopg2 libgeos-dev libgdal-dev libspatialindex-dev cmake
      
      - uses: actions/checkout@v2
      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - uses: actions/cache@v2
        id: cache
        with:
          path: .cache/wheels
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Build Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          python -m pip wheel --wheel-dir=.cache/wheels -r requirements.txt
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-index --find-links=.cache/wheels -r requirements.txt
      - name: Lint with flake8
        run: |
          python -m pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          python -m pip install pytest-cov pytest-xdist[psutil]
          python -m pytest -n auto
